### ISSUE TITLE
Communication slows down after a while

### ISSUE THREAD

**Issue by cslaviero** [susundberg/pebble-linux-remote#2]
Hi there, 

I've managed to run the python script on my Mac (not big deal, just paired Pebble with my Mac, and changed the "device" variable on default.ini to match my Pebble serial port - something like /dev/cu.Pebble[...]). 

I've also managed to run apple scripts (I was trying to make my pebble work with PowerPoint, so I created some scripts to 'translate' up and down single presses to left and right button presses :) ). However, after a few seconds (not sure if they are 'idle seconds' or 'any seconds'), my button presses on Pebble are not being translated. Have you had this problem too? Do you have any clue about what may be happening? As far as I could see they are not even being sent by the Pebble app, so my guess is that it may have something to do with it. 

thanks!

**Comment by cslaviero** [comment]
update: I don't think it has to do with Pebble app anymore, since when I close and open it again, the problem remains, but when I restart the python script, everything goes back to normal. However after around 40~45 seconds, it starts taking around 2 seconds to respond to my presses.

**Comment by susundberg** [comment]
Hi! And sorry for slow response! Nice to hear its at least somewhat workable with Mac! And sorry for it not working good enough.

As i do not have Apple i cannot debug the issue. I have not noticed such behaviour with linux, but again, i have tested the app only with single kernel version. 

I would suggest, if you still have time to dig the issue, that you set the loglevel to DEBUG and add extra debug line after line 81 "subprocess_call ..." -- something like `logging.debug("Call done")` -- that way you should be sure that 1) the calls are received by the pebble and 2) the actual system calls are no taking extra time. Assuming the (1) will fail, then we would need to dig up why the messages are not getting delivered to the `CommandHandler`

**Comment by cslaviero** [comment]
I've tried what you suggested but it seems that these messages are not being received. I couldn't debug the pebble app with "pebble logs" at the same time I was using it since it can't connect twice to the same serial BT port. Due to this I changed the connection type to websockets, which works ok. It's not perfect because it has some hiccups when sending the message to your script when inactive for a while, but it does not "slows down" after ~40 seconds as when connecting directly over BT. 

I'll try to check if updating pyserial to a newer version change something. 
edit: nothing changed, unfortunately :(

**Comment by susundberg** [comment]
Hi again, and sorry again for late reply. I promise to be faster if you still have time and willness to debug the issue.

To dig deeper; one could fire up wireshark or similar (not sure how these work with mac) to make sure the bluetooth protocol layer packages are beeing sent and received.

Above my code is the libpebble code, and above that is the os-level. The libpebble2 ( from https://github.com/pebble/libpebble2 ) could at least in theory could be eating the input, but to me the code looked fine and clean. You could -- if you want to add some logs there, specifically `libpebble2/communication/transports/serial.py:45`  to see if data is coming out from the linux socket as it should.

One simple solution also popped my mind: you have disabled other paired devices bluetooth when you try to use the mac connection -- right?

**Comment by cslaviero** [comment]
Hey @susundberg ,

well, I've checked if the read_packet() function was receiving any message during this "delay time", but it turns that it is not. Looking even further, it seems that the same issue happens when I use "pebble logs --serial </dev/cu.[...]> ": after ~45 seconds, it starts to take ~1 second to print any log message on terminal. So either it has something to do with pyserial (which I don't think it has), or it is something happenning at the os-level. I'll try to check how are packets being sent/received on the BT stack with wireshark later this week and reach back to you if I have any news. Maybe if I find it has something to do with the OS level, I'll contact the guys who created pyserial to see if they had any of these issues. First I want to be sure it's something they could help me (us) :)

**Comment by susundberg** [comment]
My guess would be the same. You could also try to ping libpebble2 developer -- she was online at least at some point at Freenode #pebble -- the library serial port defaulted to a mac-look-a-like serial device.

Good luck!

**Comment by cslaviero** [comment]
I've downloaded the "Hardware IO Tools" to get the "PacketLogger" app to check packets from the BT connection, since this was the only possible way to do it (wireshark says it does not support packet logging for BT on Mac, only packet analysis). As far as I could see, it seems that after 50 seconds that the Pebble is connected, the connection "mode" changes to "Sniff mode". I'm almost 100% sure that is what is causing the Pebble to be listened less often. Now I guess I have enough information to talk to katharine and the guys from Pebble :)

Since this is not specifically an issue from your code, you can close this issue report if you need. Thanks a lot for your help :) I'll keep you updated when I have any news about this.

**Comment by cslaviero** [comment]
@susundberg one last thing: could you check if if this "mode change" happens when on Linux? I'm thinking that this mode should change back again to "active mode"  when it "hears" something, but it is not doing it (at least on my Mac). I'd like to see if this second mode change happens on Linux.

**Comment by susundberg** [comment]
I will check that - but it will have to wait until monday, sorry. 

About entering the "sniff" state: there is - or at least is supposed to be - a periodic (actually 10s) PING that is sent to the pebble-app -- and the pebble app reacts to it (background color - idea: you will notice that you are fucked before slide change is stuck). Now - as the protocol says - the pebble watch will reply to this with ACK - so it should be communicating at least single package every 10s.

The ping sending is at `pebble_app/src/communication.c:68` on pebble side and `host_python/pebble_connection.py:189` on python side 

You should be seeing that on your package log -- i guess you did -- so the weird thing is - why does it enter 'sniff mode' if the communication channel is "clearly in use". Imho 10s timeout would sound like so small thats its probably not the case, but i am guessing here.

**Comment by cslaviero** [comment]
Yeah I've seen this ping and even tried to change it to see it it could prevent this mode from happening, but had no sucess. It turns that the connection goes to "sniff mode" in even while I'm sending packets (by pressing buttons constantly). So, well, sound like a bug to me, I'm just not sure if is Pebble who is responsible for changing this mode or the BT stack on Mac. If my calculations are correct ( :) )... it's Pebble's fault, and affects only OS X.

I've just submitted a support request to them, let's see what they say about this.

**Comment by susundberg** [comment]
Hi again. I had the pebble hooked up today and it seems like to me (with no real bluetooth protocol experience) that it does enter to sniff mode around 50s, and then again "mode change" -  "mode change ( Exit sniff mode )" exits it every 10s (i guess thats the ping). The app keeps good response rate -- the response is almost immediate (less than 1s delay after button press is displayed on pebble) .

Ping me with an email address if you want full BT-log -- i will not the attach it here as public since i am not sure what all information it contains and i am not sure how useful it will be. Below is part of the capture -- with most of data hidden.

![screenshot from 2015-10-25 21 48 55](https://cloud.githubusercontent.com/assets/2778357/10717491/3b430a26-7b62-11e5-96d6-7ae3fd20d625.png)

**Comment by cslaviero** [comment]
Hey @susundberg , thanks, I'd like to see the logs. My e-mail is my github username at gmail :) Pebble Support replied to me and said it could take a while for them to answer (and I'm not sure if they will put this issue as a priority :( ), but maybe we can find a way to bypass it , who knows :)

**Comment by susundberg** [comment]
Update; @cslaviero has been digging up the issue, and seems like the issue would be non-project related bug -- new OG pebble seems not to be suffering from the delay. Testing continues.

**Comment by susundberg** [comment]
Closing as inactive
