### ISSUE TITLE
Serial connection to Pebble interferes with Bluetooth audio

### ISSUE THREAD

**Issue by edgex004** [susundberg/pebble-linux-remote#4]
Thank you for this app! This is exactly what I've been looking for while I investigate cobbling together a linux client based on libpebble2.

At the moment, I can't seem to output audio to Bluetooth speakers at the same time as running this app. Not positive why, but I'm thinking it is because this app immediately sends another message as soon as it receives a response from the pebble and acts accordingly.

Is it possible that some sort of adjustable delay could be implemented to reduce the number of messages that are sent? I'm thinking this would have to be user-definable, as it would affect responsiveness. I tried adding an additional time.sleep(1) at the start of the while loop in the host script, but this caused the app to not be able to start a connection.

**Comment by susundberg** [comment]
Hi! Thanks!

The app indeed certain low traffic communication over bluetooth going on at all the times -- it sends ping messages (by default once in every 10s [1] ). You could try to change this to say 60s (the pebble app will then "timeout" every time [2], but this is just to test does it solve the issue.. ) 

When user presses a key in pebble, it will send a message right-a-way and the host will send corresponding ACK (i think) and that is not changeable by this project only - you would need to dig quite deep into pebble os (i guess).

Anyway, as far as i know, there should be no reason why you could not do two blue tooths at the same time. It sounds bit weird and troublesome. The bluetooth speaker work fine when the app is not running i guess? And the connection with the app works fine when the bluetooth speaker is not involved? Does  `dmesg` does not show anything weird? Does the speaker work fine with some other bluetooth traffic (example: file transfer to phone) ? 

[1] https://github.com/susundberg/pebble-linux-remote/blob/master/host_python/pebble_connection.py#L200
[2] https://github.com/susundberg/pebble-linux-remote/blob/master/pebble_app/src/main.c#L23

**Comment by edgex004** [comment]
Ah interesting. That 10 second delay is simply a ping for connection verification, and it should continue to wait 10 seconds on a successful ping. I will need to look at the code more closely and see how you are using the Pebble API.

I was confused and thinking that the sleep(10) command would be interrupted by a successful ping response from the watch, and therefore the script would in fact only delay 10 seconds if there were no response from the pebble. I was thinking this would mean you would be sending non-stop pings if the response was successful, but your idea makes more sense.

I will perhaps try connecting to another device to see if the same issue occurs. I will let you know after I collect a few more details this week. Thank you for the info.

EDIT: Also, the speaker works fine on its own, and the connection with the app works fine alone. When the two are used together they seem to interfere.

**Comment by aveao** [comment]
necroing, but have you tried using another Bluetooth dongle? Some bluetooth chips (for ex. one on Pebble) only supports 1 concurrent connection.

**Comment by edgex004** [comment]
After a lot more testing, this was a hardware issue. I got my headset and your pebble app to work concurrently, so you should mark this as resolved. I realized that my trouble was coming from heavy wifi use at the same time as using BT. I believe wifi and BT share an antenna for my unit and are causing problems for each other.
