### ISSUE TITLE
Error importing ConfigParser module (arch linux)

### ISSUE THREAD

**Issue by klundry** [susundberg/pebble-linux-remote#5]
When I try to start pebble_connection.py it fails with the error 

`Traceback (most recent call last):
  File "pebble_connection.py", line 10, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'`

I believe I have all the required packages installed.

**Comment by klundry** [comment]
Hey, I'm having a little trouble getting this going.  I've tried it also on raspbian and I'm a lot closer, but it's still not working.  Where is the best place to get help making it work?  I don't really want to open an issue for everything because it's probably my own inability that is the problem.

**Comment by susundberg** [comment]
Hi! Sorry for late reply! The ConfigParser is standard module in python 2.7 -- it should be there. Are you maybe using python 3? What does `python --version` say?

I havent found time to port the code to python3 -- but if you have time and eagerness i will definitely merge the pull request.

**Comment by susundberg** [comment]
Closing as inactive
